# Generated by Django 5.2.6 on 2026-08-13 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dwlr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "level_mbgl",
                    models.FloatField(
                        help_text="metres below ground level; -ve = above ground"
                    ),
                ),
                ("samples", models.SmallIntegerField(default=1)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("state", models.CharField(db_index=True, max_length=80)),
                ("district", models.CharField(db_index=True, max_length=80)),
                ("tehsil", models.CharField(blank=True, max_length=80)),
                ("block", models.CharField(blank=True, max_length=80)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("agency", models.CharField(default="CGWB", max_length=40)),
                ("well_type", models.CharField(blank=True, max_length=60)),
                ("aquifer_type", models.CharField(blank=True, max_length=60)),
                ("well_depth_m", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("latest_level_mbgl", models.FloatField(blank=True, null=True)),
                ("latest_date", models.DateField(blank=True, null=True)),
                ("mean_level_mbgl", models.FloatField(blank=True, null=True)),
                ("min_level_mbgl", models.FloatField(blank=True, null=True)),
                ("max_level_mbgl", models.FloatField(blank=True, null=True)),
                ("pre_monsoon_mbgl", models.FloatField(blank=True, null=True)),
                ("post_monsoon_mbgl", models.FloatField(blank=True, null=True)),
                ("seasonal_fluctuation_m", models.FloatField(blank=True, null=True)),
                (
                    "trend_m_per_year",
                    models.FloatField(
                        blank=True,
                        help_text="+ve = water table deepening (depletion)",
                        null=True,
                    ),
                ),
                ("recharge_mm", models.FloatField(blank=True, null=True)),
                ("specific_yield", models.FloatField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("semi_critical", "Semi-Critical"),
                            ("critical", "Critical"),
                            ("over_exploited", "Over-Exploited"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "data_quality",
                    models.FloatField(blank=True, help_text="0-100", null=True),
                ),
                ("anomalies", models.JSONField(blank=True, default=list)),
                ("reading_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="WaterQualityRecord",
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["state", "district"], name="dwlr_statio_state_4ef1db_idx"
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="dwlr.station",
            ),
        ),
        migrations.AddIndex(
            model_name="reading",
            index=models.Index(
                fields=["station", "-date"], name="dwlr_readin_station_b6c74a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reading",
            unique_together={("station", "date")},
        ),
    ]
