# Generated by Django 5.2.6 on 2026-08-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dwlr", "0002_reading_station_delete_waterqualityrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("payload", models.JSONField()),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
